package de.mfthub.model.entities.enums;

public enum DeliveryState {
   INITIATED,
   FILES_INBOUND,
   PROCESSING_READY,
   PROCESSING_DONE,
   OUTBOUND_READY,
   FILES_SEND,
   SUCCESS,
   AUTO_RECOVERABLE_ERROR,
   NON_AUTO_RECOVERABLE_ERROR
}
